# Generated by Django 2.1.3 on 2018-12-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getaband', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instrument', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='aboutMe',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='urls',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getaband.User'),
        ),
        migrations.AddField(
            model_name='instruments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getaband.User'),
        ),
    ]
